Select FM.NOMBRE, P.NOMBRE, PROD.Descripcion, FROM Mensaje as MSJ
INNER JOIN Proyecto as P ON MSJ.PROYECTO = P.PROYECTO
INNER JOIN Producto as PROD ON MSJ.PRODUCTO = PROD.PRODUCTO
INNER JOIN FORMATO_MENSAJE as FM ON MSJ.COD_FORMATO = FM.COD_FORMATO 
